### ISSUE TITLE
WifiInfoPlugin not working for phonegap 1.9.0

### ISSUE THREAD

**Issue by cwmillsmsc** [hungtatai/Cordova-WifiInfoPlugin#1]
I am building an app with AppLaud in eclipse using cordova/phonegap 1.9.0 the ctx.getApplicationContext() function on line 20 of the wifiInfoPlugin.java file is no longer supported. By rolling back to cordova/phonegap 1.6.1 it is now supported. I am having another issue now however, upon running my app(on device), I get the error:
Uncaught TypeError: cannot call method 'get' of undefined asset/www/index.js: 15. 
Thanks, 
Cameron

**Comment by hungtatai** [comment]
Thanks for your report. I've fixed it.
Enjoy!
