### ISSUE TITLE
Can't get it to work on Cordova 3.4

### ISSUE THREAD

**Issue by as4565683** [hungtatai/Cordova-WifiInfoPlugin#5]
Hello,

sorry but I can't get it to work on Cordova 3.4.

Installed with:
$ cordova plugin add https://github.com/binaryforce/phonegapplugin-wifiutility.git

To build it, I had to change this:

import org.apache.cordova.api.CallbackContext;
import org.apache.cordova.api.CordovaPlugin;

to:

import org.apache.cordova.CallbackContext;
import org.apache.cordova.CordovaPlugin;

But still it did not work...

All the best!

**Comment by manrueda** [comment]
Hi, i just make a fork of the plugin and support Cordova 3.4.

https://github.com/ManRueda/org.apache.cordova.wifiinfo

**Comment by hungtatai** [comment]
@ManRueda Thank you for your help :smile:
